name: Test gatsby-remark-double-parenthesis-link

on:
  pull_request:
    paths:
      - "packages/gatsby-remark-double-parenthesis-link/**"
  push:
    paths:
      - "packages/gatsby-remark-double-parenthesis-link/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install root
        run: npm ci

      - name: Install plugin
        run: npm ci
        working-directory: packages/gatsby-remark-double-parenthesis-link

      - name: Build plugin
        run: npm run build
        working-directory: packages/gatsby-remark-double-parenthesis-link
      # - run: npm run test
