name: Test gatsby-source-roamresearch

on:
  pull_request:
    paths:
      - "packages/gatsby-source-roamresearch/**"
  push:
    paths:
      - "packages/gatsby-source-roamresearch/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install root
        run: npm ci

      - name: Install plugin
        run: npm ci
        working-directory: packages/gatsby-source-roamresearch

      - name: Build plugin
        run: npm run build
        working-directory: packages/gatsby-source-roamresearch
      # - run: npm run test
