name: Test gatsby-transformer-markdown-references

on:
  pull_request:
    paths:
      - "packages/gatsby-transformer-markdown-references/**"
  push:
    paths:
      - "packages/gatsby-transformer-markdown-references/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Install root
        run: npm ci

      - name: Install plugin
        run: npm ci
        working-directory: packages/gatsby-transformer-markdown-references

      - name: Build plugin
        run: npm run build
        working-directory: packages/gatsby-transformer-markdown-references
      # - run: npm run test
